language: minimal

services: docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - DOCKER_COMPOSE_VERSION=1.23.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
  - chmod +x kubectl
  - sudo mv kubectl /usr/local/bin/

install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t wolfgangbecker/udacity-c4-proxy:latest -t wolfgangbecker/udacity-c4-proxy:$SHA -f ./course-03/exercises/proxy/Dockerfile ./course-03/exercises/proxy
  - docker build -t wolfgangbecker/udacity-c4-frontend:latest -t wolfgangbecker/udacity-c4-frontend:$SHA -f ./course-03/exercises/udacity-c2-frontend/Dockerfile ./course-03/exercises/udacity-c2-frontend
  - docker build -t wolfgangbecker/udacity-c4-user-api:latest -t wolfgangbecker/udacity-c4-user-api:$SHA -f ./course-03/exercises/udacity-c2-restapi-user/Dockerfile ./course-03/exercises/udacity-c2-restapi-user
  - docker build -t wolfgangbecker/udacity-c4-feed-api:latest -t wolfgangbecker/udacity-c4-feed-api:$SHA -f ./course-03/exercises/udacity-c2-restapi-feed/Dockerfile ./course-03/exercises/udacity-c2-restapi-feed
  - docker push wolfgangbecker/udacity-c4-proxy:latest
  - docker push wolfgangbecker/udacity-c4-frontend:latest
  - docker push wolfgangbecker/udacity-c4-user-api:latest
  - docker push wolfgangbecker/udacity-c4-feed-api:latest
  - docker push wolfgangbecker/udacity-c4-proxy:$SHA
  - docker push wolfgangbecker/udacity-c4-frontend:$SHA
  - docker push wolfgangbecker/udacity-c4-user-api:$SHA
  - docker push wolfgangbecker/udacity-c4-feed-api:$SHA

deploy:
  - provider: script
    script: scripts/deploy.sh
    on:
      branch: master
