version: '2'

services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - user-api
      - feed-api
  frontend:
    build:
      context: ./udacity-c2-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
  user-api:
    build:
      context: ./udacity-c2-restapi-user
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    env_file: .env
  feed-api:
    build:
      context: ./udacity-c2-restapi-feed
      dockerfile: Dockerfile
    ports:
      - "6000:8080"
    env_file: .env

